version: '3.8'
services:
# ########################################
# # datamanager MANAGER SERVICE
# #######################################
  
#   ############## SERVICE #################
  datamanager:
    image: davidohhana/newsai-data_manager:latest
    container_name: newsai_data_manager
    ports:
      - '7001:7001'
      - "5006:5005"
    networks:
      - News_app_network
    restart: unless-stopped


 

# ########################################
# # news manager MANAGER SERVICE
# #######################################
  
#   ############## SERVICE #################
  newsmanager:
    image: davidohhana/newsai_news-manager:latest
    container_name: newsai_news_manager
    ports:
      - '7000:7000'
      - "5000:5005"
    networks:
      - News_app_network
    restart: unless-stopped




# ########################################
# # USER ACCESSOR SERVICE
# #######################################
  
# ########## SERVICE ################
  useraccessor:
    image: davidohhana/newsai_user-accessor:latest
    container_name: user_accessor_newsAi
    ports:
      - '7002:7002'
      - "5005:5005"
    depends_on:
      - postgres

    networks:
      - News_app_network
    restart: unless-stopped



# #######################################
# # newsdata_io_accessor  SERVICE
# ######################################
  
#   ########## SERVICE ###################
  newsdataioaccessor:
    image: davidohhana/news_data_io_accessor:latest
    container_name:  newsdata_io_accessor_newsAi
    ports:
      - '7003:7003'
      - "5008:5005"
    networks:
      - News_app_network
    restart: unless-stopped

# ########################################
# # llm_accessor SERVICE
# #######################################
  
#   ########## SERVICE ###################
  llmaccessor:
        image: davidohhana/newsai_llm_accessor:latest
        container_name:  llm_accessor_newsAi
        networks:
          - News_app_network
        restart: unless-stopped


# ########################################
# # MAIL SENDER SERVICE
# #######################################

  mailsenderengine:
    image: davidohhana/mailsender_engine:latest
    container_name:  mail_sender_engine_newsAi
    ports:
      - '7005:7005'
      - "5009:5005"
    networks:
      - News_app_network
    restart: unless-stopped
      

# ########################################
# # GATEWAY
# #######################################

  gateway:
    image: davidohhana/newsai_gateway:latest
    container_name:  newsai_gateway
    ports:
      - '8080:8080'
      
    networks:
      - News_app_network
    restart: unless-stopped
# # ########################################
# # # TINY URL
# # #######################################

#   tinyurl:
#     image: davidohhana/newsaitinyurl:latest
#     container_name:  tinyurl_newsai
#     ports:
#       - '7008:7008'
#     depends_on:
#       - redis
#     networks:
#       - News_app_network
#     restart: unless-stopped
########################################
# DATA BASES
########################################
##########################
# USER DB
##########################
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./userData:/var/lib/postgresql/data
    networks:
      - News_app_network
    privileged: true
# ###############################
# # SHORT URL DB
# ##############################
#   redis:
#     image: redis
#     command: redis-server --bind 127.0.0.1
#     ports:
#       - "127.0.0.1:6379:6379"
#     networks:
#       - News_app_network
#     volumes:
#       - ./urlData:/data
#     privileged: true
########################################
# ZOOKEEPER
#######################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - News_app_network
########################################
# KAFKA
#######################################   
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure
    networks:
      - News_app_network

#########################################
# DOCKER-COMPOSE CONFIGURATIONS
#########################################
volumes:
  userData:
  urlData:
networks:
  News_app_network:
    name: News_app_network
 
