version: '3.8'
services:
# ########################################
# # datamanager MANAGER SERVICE
# #######################################
  
#   ############## SERVICE #################
  datamanager:
    image: davidohhana/newsai-data_manager:latest
    container_name: newsai_data_manager
    ports:
      - '7001:7001'
    networks:
      - News_app_network
    restart: unless-stopped


 

# # ########################################
# # # news manager MANAGER SERVICE
# # #######################################
  
# #   ############## SERVICE #################
  newsmanager:
    image: davidohhana/newsai_news-manager:latest
    container_name: newsai_news_manager
    ports:
      - '7000:7000'
    networks:
      - News_app_network
    restart: unless-stopped




# ########################################
# # USER ACCESSOR SERVICE
# #######################################

  keycloak:
      image: quay.io/keycloak/keycloak:latest
      container_name: keycloak
      restart: always
      command: start-dev
      environment:
          KC_DB: postgres
          KC_DB_URL: jdbc:postgresql://postgres/NewsAiDB
          KC_DB_USERNAME: postgres
          KC_DB_PASSWORD: postgres
          KC_HOSTNAME: localhost
          KC_HOSTNAME_PORT: 8081
          KEYCLOAK_ADMIN: admin
          KEYCLOAK_ADMIN_PASSWORD: admin
      ports:
          - "8081:8080"
      networks:
        - News_app_network
      depends_on:
          - postgres
  

# ########################################
# # llm_accessor SERVICE
# #######################################
  
#   ########## SERVICE ###################
  llmaccessor:
        image: davidohhana/newsai_llm_accessor:latest
        container_name:  llm_accessor_newsAi
        networks:
          - News_app_network
        restart: unless-stopped


# ########################################
# # MAIL SENDER SERVICE
# #######################################

  mailsenderengine:
    image: davidohhana/mailsender_engine:latest
    container_name:  mail_sender_engine_newsAi
    ports:
      - '7005:7005'
    networks:
      - News_app_network
    restart: unless-stopped
      

# # ########################################
# # # GATEWAY
# # #######################################

  gateway:
    image: davidohhana/newsai_gateway:latest
    container_name:  newsai_gateway
    ports:
      - '8080:8080'
    networks:
      - News_app_network
    restart: unless-stopped
# # ########################################
# # # TINY URL
# # #######################################

#   tinyurl:
#     image: davidohhana/newsaitinyurl:latest
#     container_name:  tinyurl_newsai
#     ports:
#       - '7008:7008'
#     depends_on:
#       - redis
#     networks:
#       - News_app_network
#     restart: unless-stopped
########################################
# DATA BASES
########################################
##########################
# USER DB
##########################
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./userData:/var/lib/postgresql/data
    networks:
      - News_app_network
    privileged: true
# ###############################
# # SHORT URL DB
# ##############################
#   redis:
#     image: redis
#     command: redis-server --bind 127.0.0.1
#     ports:
#       - "127.0.0.1:6379:6379"
#     networks:
#       - News_app_network
#     volumes:
#       - ./urlData:/data
#     privileged: true
########################################
# ZOOKEEPER
#######################################
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
    networks:
      - News_app_network
########################################
# KAFKA
#######################################   
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    restart: on-failure
    networks:
      - News_app_network

#########################################
# DOCKER-COMPOSE CONFIGURATIONS
#########################################
volumes:
  userData:
  urlData:
networks:
  News_app_network:
    name: News_app_network
 
