apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: api.deletePreferencec
spec:
  type: bindings.kafka
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: kafka:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: deletePreferencec
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: deletePreferencec
  - name: AuthType
    value: none
  - name: direction
    value: output
  - name: maxMessageBytes # Optional.
    value: 65536
