apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: api.updateLanguege
spec:
  type: bindings.kafka
  version: v1
  metadata:
  # Kafka broker connection setting
  - name: brokers
    value: kafka:9092
  # consumer configuration: topic and consumer group
  - name: topics
    value: updateLanguege
  - name: consumerGroup
    value: group1
  # publisher configuration: topic
  - name: publishTopic
    value: updateLanguege
  - name: AuthType
    value: none
  - name: direction
    value: output
  - name: consumerID # Optional. If not supplied, runtime will create one.
    value: "manager"
  - name: clientID # Optional. Used as client tracing ID by Kafka brokers.
    value: "updateLanguege"
 
  - name: consumeRetryInterval # Optional.
    value: 200ms
  - name: maxMessageBytes # Optional.
    value: 65536
